---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
library(mixtools)
source("fsir.R")
source("functions_ADR.R") ### some functions for ADR - By Wang and Yin (2019)
library(dr)
library(np)
library(CVarE)
library(MAVE)

n<-500
p<-10
d<-1  ## or d=1 for model 4
h<-5
b0 <- c(1,1,rep(0,p-2))
# b0 <- cbind(c(1,0,rep(0,p-2)),c(0,1,rep(0,p-2)))
# b0 <- cbind(c(1,1,0,0,rep(0,p-4)),c(0,0,1,1,rep(0,p-4)))

### setting of mu for model 1
# mu1 <- c(-1.5,-1.5,-1.5,rep(0,p-3))
# mu2 <- -mu1

### setting of mu for model 2
# mu1 <- c(-0.8,-0.8,-0.8,rep(0,p-3))
# mu2 <- -mu1
 
### setting of mu for model 3
# mu1 <- -rep(2/sqrt(p),p)
# mu2 <- -mu1

### setting of mu for model 4
mu1 <- c(2,2,0,rep(0,p-3))
mu2 <- c(0,0,0,rep(0,p-3))
mu3 <- c(-2,2,0,rep(0,p-3))


### for model 1, r1=0.5, r2=0.5
### for model 2, r1=0.5, r2=-0.5
### for model 3, r1=0.5, r2=-0.5
### for model 4, r1=0.3, r2=0, r3=-0.3
r1 <- 0.3
r2 <- -0.3
sig1<-diag(1,p)
sig2<-diag(1,p)
for (i in 1:p)
 for (j in 1:p)
  {
   sig1[i,j]=r1^(abs(i-j))
   sig2[i,j]=r2^(abs(i-j))
  }
pm<-0.5    #### balanced case, or set pm=0.1, pm=0.3 for unbalanced case


M<-200
val<-matrix(0,6,M)
bia<-matrix(0,6,M)
for (i in 1:M)
{
  options(warn=-1)
  #### for model 1, model 2, model 3
  # w<-rbinom(n,size=1,prob=pm)
  # x1<-t(t(matrix(rnorm(n*p),,p)%*%matpower(sig1,0.5))+mu1)
  # x2<-t(t(matrix(rnorm(n*p),,p)%*%matpower(sig2,0.5))+mu2)
  # x<-x1*(1-w) + x2*w
  
  ####  for model 4
  x1<-t(t(matrix(rnorm(n*p),n,p)%*%matpower(sig1,0.5))+mu1)
  x2<-t(t(matrix(rnorm(n*p),n,p))+mu2)
  x3<-t(t(matrix(rnorm(n*p),n,p)%*%matpower(sig2,0.5))+mu3)
  w<-rbinom(n,size=2,prob=pm)
  x<-x1*(w==0)+x2*(w==1)+x3*(w==2)
  
  ####  use BIC to determine the number of clusters ### 
  cutpts <- 100*(-10:10)
  datamult <- makemultdata(x, cuts = cutpts)
  cn <- multmixmodel.sel(datamult, comps = 1:4, epsilon = 0.001)
  q <- cn["BIC","Winner"]
  
  # y <- sign(x[,1])*log(abs(x[,2]+3+rnorm(n) ))          ### model 1
  # y <- sign(x[,1])*(5-x[,1]^2+x[,2]^2) +0.5*rnorm(n)    ### model 2
  # y <- (x[,1]+x[,2])^2+exp(x[,3]+x[,4])*rnorm(n)        ### model 3
  pr <- 1/(1+exp(-2*(x[,1]+x[,2]+2)))
  y <- rbinom(n,size=1,prob=pr)                         ### model 4


  ## SIR_M
  res <- SIR_M(x,y,q,d,h)
  b1 <- res$beta
  bia[1,i]<-dv(b1,b0)

  ## SIR_RM
  b2 <- SIR_RM(x,y,q,d,h,b1,res$para)$beta
  bia[2,i]<-dv(b2,b0)
  
  ## SIR
  b3<-dr(y~x,method="sir",nslices=h)$evectors[,1:d]
  bia[3,i]<-dv(b3,b0)

  ## ADR
  b4<-knnsir(x,y,d,4*p)
  bia[4,i]<-dv(b4,b0)

  ## MAVE
  b5<- mave(y~x,method="meanMAVE")$dir[[d]]
  bia[5,i]<-dv(b5,b0)

  ## CVE
  b6 <- cve(y~x,method="central",max.dim = d)$res$`1`$B
  bia[6,i]<-dv(b6,b0)

  print(i)
} 
m2<-apply(bia,1,mean) 
s2<-apply(bia,1,sd) 
output2<-matrix(c(m2,s2),2,6,byrow = TRUE)   
column=c("SIR_M","SIR_RM","SIR","ADR","MAVE","CVE")   
row=c("mean of bias","sd of bias")  
dimnames(output2)=list(row,column)  
output2 
```
```{r}
bia
```















